# Generated by Django 4.1.5 on 2023-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='mood',
            field=models.TextField(null=True),
        ),
    ]
